defaultBaseImage: ko.local/kc-base
builds:
  - id: kapp-controller
    main: ./cmd/
    flags:
    - -mod=vendor
    - -trimpath
    ldflags:
    - -X main.Version={{or (index .Env "VERSION") "develop"}}
