name: Trivy CVE Dependency Scanner

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan-all:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go 1.x
        uses: actions/setup-go@v1
        with:
          go-version: "1.17"
      - name: Build the kapp-controller artifacts
        run: |
          ./hack/install-deps.sh
          ./hack/build.sh

          # docker image
          docker build -t docker.io/carvel/kapp-controller:${{ github.sha }} .
      - name: Install Trivy
        run: |
          brew install aquasecurity/trivy/trivy

          # download the sarif format template
          git clone --depth 1 https://github.com/aquasecurity/trivy
      - name: Run Trivy Reports
        run: |
          # kapp-controller binary - sarif
          trivy rootfs --ignore-unfixed --format template --template "@trivy/contrib/sarif.tpl" \
            --output trivy-results-binary.sarif --severity "MEDIUM,HIGH,CRITICAL" \
            "controller"

          # kapp-controller docker image - sarif
          trivy image --ignore-unfixed --format template --template "@trivy/contrib/sarif.tpl" \
            --output trivy-results-image.sarif --severity "MEDIUM,HIGH,CRITICAL" \
            "docker.io/carvel/kapp-controller:${{ github.sha }}"

          # kapp-controller docker image - json
          trivy rootfs --ignore-unfixed --format json \
            --output trivy-results-binary.json --severity "MEDIUM,HIGH,CRITICAL" \
            "controller"

          # kapp-controller docker image - json
          trivy image --ignore-unfixed --format json \
            --output trivy-results-image.json --severity "MEDIUM,HIGH,CRITICAL" \
            "docker.io/carvel/kapp-controller:${{ github.sha }}"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: '.'
      - name: Check for new Vulnerabilities
        run: |
          set -o pipefail

          summary="Trivy scan has found new vulnerabilities - check https://github.com/vmware-tanzu/carvel-kapp-controller/security/code-scanning for more"

          vulnCountBinary=$(jq '[ .Results[].Vulnerabilities ] | length' trivy-results-binary.json)
          vulnCountImage=$(jq '[ .Results[].Vulnerabilities ] | length' trivy-results-image.json)
          if [ $vulnCountImage -eq 0 && $vulnCountBinary -eq 0 ]; then
            summary="Trivy Scan has not found any new Security Issues"
          fi

          echo "SUMMARY=$summary" >> $GITHUB_ENV
      - name: Send Slack Notification
        if: success()
        uses: slackapi/slack-github-action@v1.15.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: G01FTP43JMQ
          slack-message: "${{ env.SUMMARY }}"
      - name: Send Failure notification
        if: failure()
        uses: slackapi/slack-github-action@v1.15.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: G01FTP43JMQ
          slack-message: "Trivy scan workflow failed. Please check the latest github action run for trivy scanner."
