name: upgrade-testing
"on":
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test-all:
    name: Upgrade Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.6"
      - name: Check out code
        uses: actions/checkout@v3.0.1
      - name: Install Carvel Tools
        run: ./hack/install-deps.sh
      - name: Run Upgrade Test
        run: |
          set -e -x

          curl -sLo /tmp/kb.deb https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases/download/v0.1.5/kubectl-buildkit_0.1.5_amd64.deb
          sudo dpkg -i /tmp/kb.deb

          minikube start --driver=docker --wait=all
          eval $(minikube docker-env --shell=bash)
          kapp deploy -a kc -f https://github.com/vmware-tanzu/carvel-kapp-controller/releases/latest/download/release.yml -y

          ./hack/deploy.sh
